### ISSUE TITLE
Default credentials for Shopware 5 missing

### ISSUE THREAD

**Issue by zsolt-szilagyi** [dockware/dockware#109]
The semi-supported SW5 surely comes with its own set of default credentials. 
For the backend, admin/shopware fails. In case they intentionally differ from the published SW6 default credentials, they should be noted on either the credentials or the SW5-page.

**Comment by martinweinmayr** [comment]
https://docs.dockware.io/use-dockware/default-credentials

its seperated as "admin credentials" > sw6

and "backend credentials" > sw5

you mean we should pack them together?
currently on e is on the top of the page one is on the bottom ...

**Comment by zsolt-szilagyi** [comment]
Ah damn, sorry. Simply missed it.
