### ISSUE TITLE
Notice on https://dockware.io/images

### ISSUE THREAD

**Issue by donserdal** [dockware/dockware#123]
Hi,

When I go to the link https://dockware.io/images I see the following: 

Notice: Undefined index: description in /var/www/html/public/images/DockerImages.php on line 58

Notice: Undefined index: description in /var/www/html/public/images/DockerImages.php on line 58

Notice: Undefined index: description in /var/www/html/public/images/DockerImages.php on line 58

Notice: Undefined index: description in /var/www/html/public/images/DockerImages.php on line 58

Notice: Undefined index: description in /var/www/html/public/images/DockerImages.php on line 58

Notice: Undefined index: description in /var/www/html/public/images/DockerImages.php on line 58

**Comment by martinweinmayr** [comment]
Many thx, for reporting fixed it :-)
