### ISSUE TITLE
watch-storefront does not work anymore

### ISSUE THREAD

**Issue by jeanfortheweb** [dockware/dockware#13]
**Describe the bug**
The watch-storefront makefile command does not work anymore since some recent version. we cannot exactly tell which version, since we used the latest image and the issue occured after a docker system prune -a today, which caused a new download of the image of course.

After some hours we found out that the .htaccess.watch file in the /html directory is no longer respected. this comes down to the fact that the apache config does not even involve this directory (anymore). moving the .htaccess.watch file to the public directory helps, but this overrides the .htaccess file then. the only real fix for us was to move the RequestHeader instructions from the .htacces.watch file in /html into the .htaccess file in /html/public

**To Reproduce**
* Pull the latest image
* Start the make watch-storefront command
* Hot reload does not work

**Expected behavior**
Hot reload should work

**Comment by boxblinkracer** [comment]
Hi 

thank you for this issue
we are already aware of, and its already fixed....about to be released with 1.3.1 soon :)

best regards
Christian

**Comment by martinweinmayr** [comment]
fixed in master, will be pushed to docker hub today
