### ISSUE TITLE
Use PCOV for PHPUnit code coverage reports

### ISSUE THREAD

**Issue by jdambacher** [dockware/dockware#140]
**Is your feature request related to a problem? Please describe.**
Xdebug is very slow when generating code coverage reports with PHPUnit in a CI pipeline.

**Describe the solution you'd like**
Pcov is way more faster than Xdebug when it comes to coverage reports (see https://geshan.com.np/blog/2020/11/phpunit-code-coverage-pcov/#quick-comparison-of-code-coverage)

Xdebug and PCOV could not be active at the same time, so it would be nice to switch it via a Makefile command or simply by setting a environment variable. We could also use the DOCKWARE_CI variable to disable Xdebug and enable PCOV.

**Comment by jdambacher** [comment]
Xdebug and PCOV could not be active at the same time, so it would be nice to switch it via a Makefile command or simply by setting a environment variable. We could also use the `DOCKWARE_CI` variable to disable Xdebug and enable PCOV.

**Comment by boxblinkracer** [comment]
Hi @jdambacher 
just did a new commit and installed it :)

**Comment by jdambacher** [comment]
Thanks, works fine 👌 reduced CI test pipeline from >20m to 12m.
