### ISSUE TITLE
Update node version

### ISSUE THREAD

**Issue by traed** [dockware/dockware#149]
Currently getting a warning when running build-administration.sh, for example:

`@Deprecated: You are using an incompatible Node.js version. Supported version range: ^16.0.0`

Seems like the image ships with Node 12 which has reached EoL.

**Comment by martinweinmayr** [comment]
which image are u using?

normally you can set it https://docs.dockware.io/features/switch-node-version

**Comment by traed** [comment]
Thanks, that works! Though having 12 as the default seems a bit dated.

**Comment by martinweinmayr** [comment]
for sure, we always looking for contributers :-)
as long as there is a solution, the change is not highest prio... 
But for sure thsi will chnage.
