### ISSUE TITLE
Missing authorization header after logged in successfully in Shopware 6 Admin

### ISSUE THREAD

**Issue by MariusWangColonia** [dockware/dockware#156]
**Describe the bug**
I am using Dockware for local development. Now I have the problem that I always get an error message (in the list of AJAX requests) when I am logged into the admin area.

**To Reproduce**
1. Start dockware with "docker run --rm -p 80:80 dockware/play:latest"
2. Go to http://localhost/admin
3. Log in
4. See  the error in the list of ajax requests

**Expected behavior**
The authorization should work flawless

**Screenshots**
![Screenshot 2023-02-06 at 11 54 21](https://user-images.githubusercontent.com/94158555/216954268-926b730d-9d63-4469-9e64-7570162bd2d9.png)
![Screenshot 2023-02-06 at 11 57 45](https://user-images.githubusercontent.com/94158555/216954451-4c0657f5-67d0-49d8-98f4-4b7f682940c5.png)

**Desktop**
 - Browser: Chrome Version 109.0.5414.119, Firefox Version 109.0.1 (64-Bit)

**Additional context**
When I open the admin area for the first timeI see that the token is passed, but I have to refresh the page manually to be directed to the admin area.
![Screenshot 2023-02-06 at 12 01 57](https://user-images.githubusercontent.com/94158555/216955249-9bf70654-9237-46ab-a0de-67a50d560eb3.png)

**Comment by boxblinkracer** [comment]
Hi there
just saw this :)

no worries, great its working now
