### ISSUE TITLE
Add PHP tooling to dev image

### ISSUE THREAD

**Issue by dithom** [dockware/dockware#159]
**Is your feature request related to a problem? Please describe.**
Right now it's not possible to use PHP tooling (linting and static analysis) inside the development images. The cause seems to be using the source of the release .zip files, which doesn't come with the `.gitlab-ci`directory holding the needed files. 

```
## ***********************************************************************
##  INSTALL SHOPWARE
## ***********************************************************************
RUN rm -rf /var/www/html/* \
    && wget --no-check-certificate https://releases.shopware.com/sw6/install_v6.4.20.0_52e67425204f8bec1d1c67608f82008710f7611b.zip -qq -O /var/www/shopware.zip \
    && unzip -q /var/www/shopware.zip -d /var/www/html \
    && rm -rf /var/www/shopware.zip
```

**Describe the solution you'd like**
Using the Shopware production template you can run:

```
composer install -d .gitlab-ci/tools
php .gitlab-ci/tools/vendor/bin/ecs check PATH_TO_CHECK --config easy-coding-standard.php
php .gitlab-ci/tools/vendor/bin/phpstan analyse PATH_TO_CHECK
```

The `composer install -d .gitlab-ci/tools` part could also be run on image build, to skip it in development and on every container restart (when vendor is excluded in the volumes). Along with it `apt-get install phpX.X-sqlite` needs to be installed for running ecs.

**Describe alternatives you've considered**
Alternatively you can build your own image based on `dockware/dev` and run these steps.

**Additional context**
For plugin developers it's very convenient to use the linting configs provided by Shopware to have valid plugin source code, when uploading plugins to the store.

**Comment by boxblinkracer** [comment]
Hi

aehm im using all kinds of dev tools from phpstan, phpunit, eslint and way more during coding and I never had any problems.
php as well as node are all fully installed in various versions.

also when running in pipelines, I would recommend using a different image or dockware/flex for dev-tools

but when it comes to run e.g. E2E tests based on Cypress for instance, then you need a Shopware,
and dockware works great for this.
The Mollie pipelines over more than 20 Shopware versions for E2E tests
https://github.com/mollie/Shopware6/actions/runs/7522706896

also there are tutorials for different CI platforms like gitlab
did you see these? https://docs.dockware.io/ci-cd/gitlab

I hope this helps you

**Comment by dithom** [comment]
Sorry for my wrong phrasing 😅 Of course you can use PHP tooling inside the images.

The issue I was facing back then, was the composer bin path, as Shopware's production template came with a dedicated `composer.json` inside `.gitlab-ci/tools`. But this has changed anyway.

Thanks for pointing out the helpful resources! I think is is resolved then 😉
