### ISSUE TITLE
(6.5.1.0+) unable to connect to MySQL from outside container

### ISSUE THREAD

**Issue by rmobis** [dockware/dockware#179]
**Describe the bug**
On versions `6.5.1.0` and `6.5.1.1` of `dockware/dev` container, I'm unable to connect to the MySQL from outside said container.

**To Reproduce**
1. Start a container with the following command:
```bash
> docker run --rm -p 3306:3306 dockware/dev:6.5.1.0
```
2. Attempt to connect to the MySQL database, using [MySQL shell](https://dev.mysql.com/doc/mysql-shell/8.0/en/):
```bash
> \connect --mysql root@localhost -proot
```
3. Observe an error the following error is thrown:
```
MySQL Error 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
```

**Expected behavior**
After step 2, you should be connected to the database with the following message:
```
Your MySQL connection id is 10
Server version: 8.0.32-0ubuntu0.22.04.2 (Ubuntu)
No default schema selected; type \use <schema> to set one.
```

**Desktop:**
 - OS: Windows 11 22H2 (build 22621.1702)
 - Browser: N/A

**Additional context**
- The issue occurs for versions `6.5.1.0` and `6.5.1.1`, but not `6.5.0.0`.
- Attempting to connect through other means (say, DataGrip) produces similar results
- Connecting from inside the container works perfectly, provided you run the mysql client as root

**Comment by sandoba** [comment]
Can confirm. It was working fine in 6.5.0.0 but reinstalling today in 6.5.1.1 and suddenly no connection possible anymore from outside, e.g. via VS Code. "docker-compose.yml" is the same as before. The container exposes the correct port as well. Inside the container normal access is possible via Adminer.

**Comment by boxblinkracer** [comment]
hi
i did already fix it in the latest master. 
ill try to push it soon :)i also need it

**Comment by boxblinkracer** [comment]
Hi there
6.5.1.1 is now pushed and working
i have troubles getting the old 6.5.x to work
but once that is done its also working there

sry for the troubles

**Comment by sandoba** [comment]
Tested in the brand new 6.5.2.1 release and it works great. Thanks!

**Comment by boxblinkracer** [comment]
perfect, thanks for letting me know :)
