### ISSUE TITLE
Docker built is broken, php7.4-fpm: unrecognized service

### ISSUE THREAD

**Issue by flowl** [dockware/dockware#185]
Using docker-compose.yml from the README.md of the "play" variant:

```
version: "3"
services:
    shopware:
      image: dockware/play:latest
      container_name: shopware
      ports:
        - "80:80"
        - "443:443"
        - "22:22"
      environment:
        - PHP_VERSION=7.4
```

Log:

```
[+] Running 73/1
 ✔ shopware 72 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                       271.8s 
[+] Building 0.0s (0/0)                                                                                                                                              
[+] Running 2/2
 ✔ Network shopware6_default  Created                                                                                                                           0.1s 
 ✔ Container shopware         Created                                                                                                                           4.7s 
Attaching to shopware
shopware  | 
shopware  |  _____   ____   _____ _  ____          __     _____  ______ 
shopware  | |  __ \ / __ \ / ____| |/ /\ \        / /\   |  __ \|  ____|
shopware  | | |  | | |  | | |    | ' /  \ \  /\  / /  \  | |__) | |__   
shopware  | | |  | | |  | | |    |  <    \ \/  \/ / /\ \ |  _  /|  __|  
shopware  | | |__| | |__| | |____| . \    \  /\  / ____ \| | \ \| |____ 
shopware  | |_____/ \____/ \_____|_|\_\    \/  \/_/    \_\_|  \_\______|
shopware  | 
shopware  | 68 69 20 64 65 76 65 6C 6F 70 65 72 2C 20 6E 69 63 65 20 74 6F 20 6D 65 65 74 20 79 6F 75
shopware  | 6c 6f 6f 6b 69 6e 67 20 66 6f 72 20 61 20 6a 6f 62 3f 20 77 72 69 74 65 20 75 73 20 61 74 20 6a 6f 62 73 40 64 61 73 69 73 74 77 65 62 2e 64 65
shopware  | 
shopware  | *******************************************************
shopware  | ** DOCKWARE IMAGE: play
shopware  | ** Tag: 6.5.3.3
shopware  | ** Version: 1.6.0
shopware  | ** Built: Thu Jul 13 11:01:32 UTC 2023
shopware  | ** Copyright 2022 dasistweb GmbH
shopware  | *******************************************************
shopware  | 
shopware  | launching dockware...please wait...
shopware  | 
shopware  | DOCKWARE: setting timezone to Europe/Berlin...
shopware  | 
shopware  | Current default time zone: 'Europe/Berlin'
shopware  | Local time is now:      Wed Jul 26 10:39:09 CEST 2023.
shopware  | Universal Time is now:  Wed Jul 26 08:39:09 UTC 2023.
shopware  | 
shopware  | -----------------------------------------------------------
shopware  | DOCKWARE: starting MySQL....
shopware  |  * Starting MySQL database server mysqld
shopware  |    ...done.
shopware  | -----------------------------------------------------------
shopware  | DOCKWARE: starting mailcatcher....
shopware  | Starting MailCatcher v0.8.2
shopware  | ==> smtp://0.0.0.0:1025
shopware  | ==> http://0.0.0.0:1080
shopware  | *** MailCatcher runs as a daemon by default. Go to the web interface to quit.
shopware  | -----------------------------------------------------------
shopware  | DOCKWARE: starting cron service....
shopware  |  * Starting periodic command scheduler cron
shopware  |    ...done.
shopware  | -----------------------------------------------------------
shopware  | DOCKWARE: switching to PHP 7.4...
shopware  | sudo service php7.4-fpm start
shopware  | php7.4-fpm: unrecognized service
shopware  | make: *** [makefile:41: switch-php] Error 1
shopware exited with code 2
```

I also see there is only a single service where webserver,mailcatcher,php and mysql are running in. That's not how Docker containers are supposed to be built.

**Comment by boxblinkracer** [comment]
no thats not the case
the dockware play and dev images are made for specific shopware versions
the latest Shopware version does not support php 7.4, so its not existing
only supported php versions of a specific shopware version are existing

there is even a commited distribution folder on github including the generated README files.
there you can see the php version of that particular image tag
https://github.com/dockware/dockware/tree/master/.dist/versions/master/play/latest

i hope this helps you

**Comment by flowl** [comment]
The [documentation at https://hub.docker.com/r/dockware/play](https://hub.docker.com/r/dockware/play) is wrong then, where it says:

> This image comes with different features that can be set with the ENV variables.
> PHP_VERSION 7.4 Switch to any of the installed PHP versions: 7.4, 7.3, 7.2,

**Comment by flowl** [comment]
Shopware 6.5 [is tested with PHPv8.1 and PHPv8.2](https://www.shopware.com/en/news/shopware-6-5/#dev-news-release-news-6-5) how come you think 7.4 is not supported when all the docs say it is?

Dockware is buggy...

**Comment by martinweinmayr** [comment]
https://github.com/shopware/platform/blob/v6.5.0.0/changelog/release-6-5-0-0/2022-12-15-limit-upper-version-of-php-constraints.md

**Comment by boxblinkracer** [comment]
hi @flowl 
so thank you for pointing out the docker hub README

docker hub README files have been maintained in the beginning before it all "escalated" (in a positive way haha).
I've just updated it and reference the website for more information

and yes, Shopware 6.5 requires a minimum version of PHP 8.1,
so that's why we don't install it, because Shopware itself wouldn't even run :)

just use

docker run --rm -p 80:80 dockware/dev:6.5.3.3 

and it works
also your docker compose above works, but you cannot set a php version to 7.4 which does not exist
if you just skip that, the default version is used of that specific image

I hope this helps

**Comment by flowl** [comment]
Thanks for your assistance, PHP 8.1 and 8.2 work well!

**Comment by boxblinkracer** [comment]
perfect :) thanks for letting me know
