### ISSUE TITLE
[Improvement] Add XDEBUG_SESSION_START to docs

### ISSUE THREAD

**Issue by alexschwarz89** [dockware/dockware#19]
Nice that xdebug comes preinstalled, i think it's worth mentioning in the docs that to debug any api route, e.g. with Postman, you can set a header XDEBUG_SESSION_START=PHPSTORM or append it as a get parameter. It will trigger a PHPStorm debug session. 

Of course if there is any other option for it, i couldn't get the remote_autostart/connect_back_on to work.

**Comment by martinweinmayr** [comment]
Thanks for giving us the idea.

It's now included in the dockware docs.

https://dockware.io/docs#debugging
