### ISSUE TITLE
Mailcatcher is not configured correctly in .env

### ISSUE THREAD

**Issue by FynnZW** [dockware/dockware#194]
After installation, mailcatcher is running but does not receive any mails.
Looking at the `.env` file, it seems the variable name has changed:

```env 
# With Shopware 6.4.17.0 the MAILER_DSN variable will be used in this template instead of MAILER_URL
# ...
MAILER_URL=smtp://127.0.0.1:1025
```

Renaming it to MAILER_DSN resolves it:
```env
MAILER_DSN=smtp://127.0.0.1:1025
```

**Version**
 - dockware/dev:6.5.5.2

**Comment by boxblinkracer** [comment]
hi
yes you are right

ill fix it
thank you for this

**Comment by boxblinkracer** [comment]
has been released :)
