### ISSUE TITLE
How to enable docker logs for shopware

### ISSUE THREAD

**Issue by Lehaa** [dockware/dockware#205]
I was wondering if we can enable docker logs for dockware so it outputs more details because at the moment I can only see the output of the entrypoint script. After the script finishes there are no more logs in **docker logs** command. 

Is there a way we can enable more logs ?

**Comment by Lehaa** [comment]
I've seen there is pimpmylog available which is great but the problem is when the container crashes those logs are gone.

I've managed to create a symlink like this: ln -sf /proc/1/fd/1 /var/www/html/var/log/dev.log which works great for 1 minute then I receive the following error:

**Comment by martinweinmayr** [comment]
this would only work for one process as only one process can log to the proc0 channel.
In our production image which is built for kubernetes php-fpm is logging to this channel.
But you would not see mysql logs for example ...

**Comment by Lehaa** [comment]
> this would only work for one process as only one process can log to the proc0 channel. In our production image which is built for kubernetes php-fpm is logging to this channel. But you would not see mysql logs for example ...

I need this only for test environments so seing just the php-fpm logs would be enough. How can you redirect those logs to /proc/1/fd/1 without getting permission issues ?

**Comment by Lehaa** [comment]
Ok so looking at the entrypoint script its performing at the end a **`tail -f /dev/null`** which can me modified to **`tail -f /var/www/html/var/log/dev.log`** and this way you can see those logs in the `docker logs` command.

Also its good to modify the monolog config file because its by default on verbose and it logs a lot of unnecessary info.
