### ISSUE TITLE
Cannot sign in to adminer with default credentials

### ISSUE THREAD

**Issue by m0t0rhektor** [dockware/dockware#206]
**Describe the bug**
When visiting localhost/adminer.php the sign in form is there, when entering the default credentials it says permission denied. Wont work on any other browser.

**Expected behavior**
Sign in to adminer.

**Desktop**
 - OS: Windows
 - Browser: Chrome, Microsoft edge
 - Version: latest
 
 EDIT: 
 Using shopware/dev image
 Can connect to database using mysql shell

**Comment by m0t0rhektor** [comment]
Im using the shopware/dev image

**Comment by boxblinkracer** [comment]
Hi there

aaa good point

with MySQL 8 somehow localhost wasnt possible anymore
but 127.0.0.1 works great

just tried it,
ill update the docs, thx for that

**Comment by m0t0rhektor** [comment]
Hey, 
Works perfectly with 127.0.0.1 <3

Thank you!

**Comment by boxblinkracer** [comment]
always happy to help
docs have also been updated
