### ISSUE TITLE
VSCode xDebug multiple Erros

### ISSUE THREAD

**Issue by DaveWoody** [dockware/dockware#21]
When i am using xDebug in VSCode i get an error as soon as i visit localhost in my IDE.
Also the page is loading infinitely.

![0MY2zZ8](https://user-images.githubusercontent.com/5037624/100020654-768fec80-2de0-11eb-879f-65db45c394db.png)

When i 'Continue' the call stack there are multiple errors appearing
![e7R4nwB](https://user-images.githubusercontent.com/5037624/100020715-90c9ca80-2de0-11eb-929a-128eb5d30008.png)

Am i missing something? Fairly new with xDebug but i thought if i go for a dev enviroment i should do it the right way.

Appreciate the help

**Comment by boxblinkracer** [comment]
Hi

oh sorry to hear this

can you show me your docker-compose.yml file?
do you have bind mounting? or without bind mounting?

depending on "WHO" throws the error we have 2 things to consider

a) if the error comes from within docker, please connect into your container and verify if that path exists

b) if the error comes from VSCode, then it might be a problem with either how xdebug is invoked or a mapping related thing


so please post me your compose, and if a) the file at least exists in the container
then we can continue 👍 

cheers
christian
