### ISSUE TITLE
Adminer Warning: Trying to access array offset on null in /usr/share/adminer/latest.php on line 1210 && ... on line 1406

### ISSUE THREAD

**Issue by filippovicari426** [dockware/dockware#221]
**Describe the bug**
Accessing Adminer and trying to search something via Search data in tables show pages worth of warning. I installed showpare/dev-tools from composer and the whole image is in dev mode

**To Reproduce**
Access adminer 
search for a table "cms_" in my case

**Expected behavior**
Should not show warning

**Screenshots**
![image](https://github.com/dockware/dockware/assets/135208015/ecf04585-db33-48e1-8ac8-734eafcd2ceb)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Chrome
 - Version  125.0.6422.144

**Additional context**
It might be just a php setting to show warning but I just wanted to point it out

Thanks for the time

**Comment by BreakingTV** [comment]
Is there any update yet? Don't want to install phpMyAdmin every time I create a dockware instance...

**Comment by jrson83** [comment]
There is [adminerevo](https://github.com/adminerevo/adminerevo), a well maintained fork of the original adminer, which has not been updated for a long time.

I can create a PR to replace the dependency if desired. Let me know.

**Comment by dg-arboro** [comment]
I second this. `adminerevo` would be great.

**Comment by axe1987** [comment]
We have a local make file (in combination with an sh file) that replaces the adminer with the adminerevo for our local development systems.
It works like a charme.

we even use some nice plugins, like faster table filters...

**Comment by jrson83** [comment]
> We have a local make file (in combination with an sh file) that replaces the adminer with the adminerevo for our local development systems.
> It works like a charme.
> 
> we even use some nice plugins, like faster table filters...

Yeah, I overwrite the adminer folder with adminerevo on initial setup.
