### ISSUE TITLE
Production Image

### ISSUE THREAD

**Issue by sawden** [dockware/dockware#23]
**Is your feature request related to a problem? Please describe.**
The official docker production solution from Shopware has been experimental for a year and doesn't seem to be working properly.

**Describe the solution you'd like**
A dockware image for productive use.

**Comment by boxblinkracer** [comment]
Hi

thank you for this issue

i think i dont get it :)
are you talking about this? https://github.com/shopware/production
the production template is working, and also used in their ZIP file release (so without github)
so i dont know where you see the experimental flag?

regarding production use....
one can use dockware for production...but its not meant for this regarding security and stuff like that
so theres no real recommendation on our side..just to say that...

**Comment by sawden** [comment]
Hi,

the README says that the Docker part is experimental:
"The DOCKERFILE and docker-compose.yml service definitions should work but are still experimental."
https://github.com/shopware/production/blob/6.3/README.md#docker

Okay I'll try to use Dockware for my production setup.
Thanks for your quick reply. :)!

**Comment by boxblinkracer** [comment]
Hi
aaa alright, the Docker setup in the production template.
Dockware has nothing to do with that....these are the Shopware docker files...now I understand

aehm ok, yes, but please make sure to have backups, maybe use an image without Adminer and so on :)
...so bottom line: please only do this if you know what you are doing (just have to say this)

:)

**Comment by boxblinkracer** [comment]
hi

can we close this issue? or is it still a thing?

**Comment by sawden** [comment]
Hi,
i found a production docker solution (https://github.com/shyim/shopware)

You can close this issue.
Thanks for your work. 💙

**Comment by boxblinkracer** [comment]
Hi

alright great
may i ask why you think this is the right choice for you?
