### ISSUE TITLE
dockware/dev not running in dev environment

### ISSUE THREAD

**Issue by reutli** [dockware/dockware#29]
I'm getting the dockware/dev running with 'docker run --rm -p 80:80 dockware/dev:latest'

If I try to use it in a dev environment with a docker-composer.yml (like your example in the docs) there are some errors. In case I'd able to avoid them, the apache is not responding to 'localhost' (what it did when I started the image with 'docker run --rm -p 80:80 dockware/dev:latest').

I put the docker-composer.yml file in my dev directory and started 'docker-compose up -d'.

**First try: Port 22 with failure:**
`ERROR: for shopware  Cannot start service shopware: Ports are not available: listen tcp 0.0.0.0:22: bind: address already in use

ERROR: for shopware  Cannot start service shopware: Ports are not available: listen tcp 0.0.0.0:22: bind: address already in use
ERROR: Encountered errors while bringing up the project.`

**Second try (deleted the Port 22 in docker-composer.yml):**
is starting but no chance to reach 'localhost'. See Apache2 error log:

`[Tue Jan 05 23:44:59.645265 2021] [ssl:warn] [pid 562:tid 139933958859712] AH01906: localhost:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jan 05 23:44:59.652183 2021] [ssl:warn] [pid 563:tid 139933958859712] AH01906: localhost:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jan 05 23:44:59.653193 2021] [mpm_event:notice] [pid 563:tid 139933958859712] AH00489: Apache/2.4.29 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Jan 05 23:44:59.653211 2021] [core:notice] [pid 563:tid 139933958859712] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 05 23:45:42.941078 2021] [proxy_fcgi:error] [pid 568:tid 139933522265856] [client 172.20.0.1:59302] AH01067: Failed to read FastCGI header
[Tue Jan 05 23:45:42.945054 2021] [proxy_fcgi:error] [pid 568:tid 139933522265856] (104)Connection reset by peer: [client 172.20.0.1:59302] AH01075: Error dispatching request to : 
[Tue Jan 05 23:45:57.552416 2021] [proxy_fcgi:error] [pid 568:tid 139933513864960] [client 172.20.0.1:59306] AH01067: Failed to read FastCGI header
[Tue Jan 05 23:45:57.552444 2021] [proxy_fcgi:error] [pid 568:tid 139933513864960] (104)Connection reset by peer: [client 172.20.0.1:59306] AH01075: Error dispatching request to : 
[Tue Jan 05 23:46:37.704680 2021] [proxy_fcgi:error] [pid 568:tid 139933497063168] [client 172.20.0.1:59314] AH01067: Failed to read FastCGI header
[Tue Jan 05 23:46:37.704982 2021] [proxy_fcgi:error] [pid 568:tid 139933497063168] (104)Connection reset by peer: [client 172.20.0.1:59314] AH01075: Error dispatching request to : 
[Tue Jan 05 23:47:46.140053 2021] [proxy_fcgi:error] [pid 568:tid 139933480261376] [client 172.20.0.1:59318] AH01067: Failed to read FastCGI header
[Tue Jan 05 23:47:46.140386 2021] [proxy_fcgi:error] [pid 568:tid 139933480261376] (104)Connection reset by peer: [client 172.20.0.1:59318] AH01075: Error dispatching request to : `

All is running on Mac OS 10.15.7, Docker version 20.10.0, build 7287ab3.

Any help or issue clearance is extremely appreciated.

Cheers
Michael

PS: see docker-composer.yml attached
[docker-compose.yml.zip](https://github.com/dockware/dockware/files/5773026/docker-compose.yml.zip)

**Comment by boxblinkracer** [comment]
Hi Michael

thanks for the message

so i think there are a few different things

the port 22 is already in use on your system.
if you start a docker container (in general, not only dockware) that uses a port that is in use, then it cannot start and says that error.
you could simply use any other port like 
ports
 - "1022:22"
 then you use 1022 to get into your container
 ...or kill the 22 port process on your machine

and the other thing...what does "docker ps" say?
i just started it and it works on my side...with HTTP by the way,..i dont know if you run it with ssl?

http://localhost/

cheers
christian

**Comment by reutli** [comment]
Hi Christian,

sure, had success in another port.
But  http://localhost is not loading!

docker ps shows:
`CONTAINER ID   IMAGE                 COMMAND            CREATED          STATUS          PORTS                                                                                                              NAMES
b529c97f8914   dockware/dev:latest   "/entrypoint.sh"   17 seconds ago   Up 15 seconds   0.0.0.0:80->80/tcp, 0.0.0.0:3306->3306/tcp, 0.0.0.0:8888->8888/tcp, 0.0.0.0:9999->9999/tcp, 0.0.0.0:1022->22/tcp   shopware`

<img width="1455" alt="Bildschirmfoto 2021-01-06 um 13 27 23" src="https://user-images.githubusercontent.com/62477965/103768515-ef5ea700-5022-11eb-97b9-2a620f0a97f0.png">

Again, when I'm loading with ''docker run --rm -p 80:80 dockware/dev:latest'' it's working like a charm....

Cheers 
Michael

**Comment by martinweinmayr** [comment]
@reutli does it works withoud xedbug?
If so pls. Make a docker pull on the image.

You can see hoe old your image really is with
Docker images |grep dockware/dev

**Comment by reutli** [comment]
yes! it works without xedbug! localhost up & running.

As I'm not that familiar with docker yet, please advise how to update / make a docker pull.

But it seems the image is fairly new, see output:
`dockware/dev            latest     892bfb6b4eaf   3 weeks ago     3.17GB`

**Comment by reutli** [comment]
I'm getting some steps further ;o)
Done a `docker pull dockware/dev` and pulled successfully newer image.

Now it works also WITH xedbug !

@martinweinmayr : can you please assist to setup the dev environment on a Mac regarding 'avoid bind-mounting'.
I added following in the docker-compose.yml
`      volumes:
         - "db_volume:/var/lib/mysql"
         - "shop_volume:/var/www/html" `

but getting error with docker-compose up -d

`ERROR: Named volume "db_volume:/var/lib/mysql:rw" is used in service "shopware" but no declaration was found in the volumes section.`

Any suggestions on that?
Thanks in advance

**Comment by martinweinmayr** [comment]
Xdebug was fixed yesterday 😎
If you have volumes in your compose or nothing in db oder filesystem then just
Docker-compose stop
Docker pul dockware/dev:latest
Docker-compose up

And to get all the new files
Local a docker cp ... to get all the files in your ide
💪

**Comment by reutli** [comment]
got and done that, thanks.
still error, see posting above with the volumes

**Comment by martinweinmayr** [comment]
Since in bavaria today is a public holiday and i have no laptop here i can publish the example
Tomorrow 🤟.
To get it as fast a sftp there is more todo then just a volume..

**Comment by martinweinmayr** [comment]
A working compose example with mysql can be found here
https://github.com/dockware/examples/blob/master/basic-dev-setup/docker-compose.yml

**Comment by martinweinmayr** [comment]
I guess you use it but not have declared it.

**Comment by reutli** [comment]
@martinweinmayr 

> Since in bavaria today is a public holiday and i have no laptop here i can publish the example
> Tomorrow 🤟.

no problem same in BaWü ;o) but I've to work anyway ...

I'm not understandung this: 
> To get it as fast a sftp there is more todo then just a volume..

What are you meaning with that?

> I guess you use it but not have declared it.
declaration ok, but where and how?

Is this


```
## ***********************************************************************
##  PERSISTENT DOCKER VOLUMES
## ***********************************************************************
volumes:
  dw__db_myshop_volume:
    driver: local
  dw__shopware_myshop_volume:
    driver: local
```

the declaration part? And if so, as I used the standard image what 'names' I've to use?

**Comment by martinweinmayr** [comment]
Yes it is!
You can use the names you want!
But you have to use the same ones in declaration as in the using part.
Same like a variable.

**Comment by martinweinmayr** [comment]
And don't!!! Use the same in two projects.

**Comment by reutli** [comment]
I think you made my day! Great, thanks.
Please allow me to ask some more questions:

I'm planning to use my own database within the docker image. So ask myself if it's possible to import that database with adminer in dockware/dev and use it after changing the '.env' file? Are there restrictions in place or to be expected?
What would be the best approach or what are the best practices?

The reason is to work with 'real' data to better evaluate the outcome.

Problem might be already installed plugins and therefore additional tables in the database, isn't it?

**Comment by martinweinmayr** [comment]
I think 90% of the dockware users working this way.
Dockware should only be a starting point.
But you can do with it what ever you want.
