### ISSUE TITLE
Dockware contribution not working as expected

### ISSUE THREAD

**Issue by reutli** [dockware/dockware#32]
I installed the dockware/dev successfully.
As I missed the psh.phar and linked platform folder, I switched to dockware/contribution.

Afterwards I made a Plugin and activated it - so far so good.
But TWIGs within my PlugIn are not read.

So I've searched for /config/packages/twig.yaml but it's not there?!

What is wrong with my environment and what's the difference between dockware/dev and dockware/contribution?
If I use dockware/dev then psh.phar and /platform is missing...

What I'm needing is just a full dev environment with all the tools, the correct template so I'd be able to develop a theme-plugin.
As for now (with dockware/contribution) my PgligIn is installed and activated but a html-twig is not used in my plugIn, although it's in the right place:

<img width="341" alt="Bildschirmfoto 2021-01-08 um 09 06 09" src="https://user-images.githubusercontent.com/62477965/103995806-41293d80-5199-11eb-9122-af5e50880995.png">

**Comment by reutli** [comment]
Now I made a complete new container with dockware/dev (knowing /platform and psh.phar is missing).
Integrated the PlugIn again, activated it, and activated the theme in Admin.

tabs.html.twig is still not read in, although it's there:
`www-data@0c4096fc9e32:~/html/custom/plugins/Tbcom/src/Resources/views/storefront/page/product-detail$ ls -la
total 8
drwxr-xr-x 2 www-data www-data 4096 Jan  8 11:28 .
drwxr-xr-x 3 www-data www-data 4096 Jan  8 11:28 ..
-rw-r--r-- 1 www-data www-data    0 Jan  8 11:31 tabs.html.twig`

**Comment by reutli** [comment]
I'd like to push that issue, because no dev possible :o(

**Comment by martinweinmayr** [comment]
can you upload your plugin here?
i don't really think that its not working.
If your file is there and you load it properly in your plugin it should work.

**Comment by reutli** [comment]
Here we are. 
Awaited reaction of front-end: Tabs are gone. But they're still there although a clean "tabs.html.twig" is loaded.
[Tbcom.zip](https://github.com/dockware/dockware/files/5797112/Tbcom.zip)

**Comment by martinweinmayr** [comment]
1. You have to change in your theme.json on Line 7
 "@tbcom" =>   "@Tbcom"
2. you have to add a base.html.twig with
{% sw_extends "@Storefront/storefront/base.html.twig" %}
3. activate your theme

cheers

ps. this has nothing todo with dockware, this is basic shopware 6 way how themes are working.

**Comment by reutli** [comment]
Oh, then I must but apologize if that was on me....!
Nevertheless, a point is not clear to me, because I have also not found in the documentation:
"you have to add a base.html.twig with
{% sw_extends "@Storefront/storefront/base.html.twig" %}"
Why and where does this need to be stored?

I didn't find this hint in the doc.
Maybe you can help me on this point?

Thanks a lot

**Comment by martinweinmayr** [comment]
Nope, but if i do not i get a error with something like "base..." not found.
So with it it works for me, as attached.
Normally i think it's not needed but i got it work with one line, so i was happy :-)
But the main goal was the Lower Uppercase typo.
If you only change this and assign your theme you will see what happens...


[Tbcom.zip](https://github.com/dockware/dockware/files/5800331/Tbcom.zip)

**Comment by reutli** [comment]
great thanks for this outstanding support for a beginner !!!
Will try and learn ;o)

**Comment by martinweinmayr** [comment]
you are welcome!
Did it worked now also for you?

**Comment by reutli** [comment]
To my shame, I have to admit that I can't currently test it. I will test it this afternoon. Thanks again. If it does not work I would contact you again ;o)

**Comment by reutli** [comment]
it works! Thanks
