### ISSUE TITLE
Contribute: MailCatcher not working

### ISSUE THREAD

**Issue by reutli** [dockware/dockware#34]
I'm using dockware:contribute.
In Mailcatcher no eMails are, which should have been sent from shopware.

Are there any special configs have to done to get this working?
I've not found some additionals in the docs...

**Comment by boxblinkracer** [comment]
hi there
actually not, i only know it has some troubles in shopware 5 (at least with the localhost one, a separate one works)
maybe the contribution version is broken?
you could adjust it in the admin to be the local mailcatcher with smtp on 1025

does that work?

**Comment by reutli** [comment]
> hi there
> actually not, i only know it has some troubles in shopware 5 (at least with the localhost one, a separate one works)
> maybe the contribution version is broken?
> you could adjust it in the admin to be the local mailcatcher with smtp on 1025
> 
> does that work?

Hi,

> you could adjust it in the admin to be the local mailcatcher with smtp on 1025
can you explain that a bit deeper please?

Tanks in advance.

**Comment by boxblinkracer** [comment]
hi

im not quite sure what you are trying to say...this are the things i asked but no answers from you..?

**Comment by Gainto** [comment]
Yes. The mailcatcher implementation seems not to work with a sw5 insance, since the mailer and port are not set.
We fixed it with setting the correct mail settings after the container started:

    docker exec -i shopware mysql -u root -proot  shopware <<< "UPDATE s_core_config_elements SET value='s:4:\"smtp\";' WHERE name='mailer_mailer';" &> /dev/null
    docker exec -i shopware mysql -u root -proot  shopware <<< "UPDATE s_core_config_elements SET value='s:4:\"1025\";' WHERE name='mailer_port';" &> /dev/null

Then it'll work :)

**Comment by boxblinkracer** [comment]
hi

thanks a lot

i actually thought that is already integrated like this, because that solution is known. weird. 
i'll double check when im back in the office. 

if that was the reason then we can finally fix this. thank you so much your help

**Comment by boxblinkracer** [comment]
the v1.4 versions of the dockware Shopware 5 images do now contain the mailcatcher config

thanks for creating this issue :)
