### ISSUE TITLE
Current generated SSL Certs are unusable in browsers like chrome and safari

### ISSUE THREAD

**Issue by ireznik** [dockware/dockware#35]
Integrate https://github.com/FiloSottile/mkcert to use trustworthy ssl certificates which are accepted by browser

**Comment by boxblinkracer** [comment]
Hi
thank you for this idea

could you give me a short feedback

so the tool installs a local CA, which should be done on the host....
that means that 

a) container need a pre installed certificate that its delivered with
b)still needs a manual installation of the CA on the host system

is that correct?

cheers
christian

**Comment by boxblinkracer** [comment]
by the way
i just saw the title

its not unusable, we indeed run https on local dev machines, also use apple pay and stuff like that in safari

you can just continue when the warning happens
so its only a warning which is kinda nice to know that you are on the local dev system and not accidentally on a real one

just to let you know that you dont have to wait for a mkcert to use it :)

**Comment by boxblinkracer** [comment]
i will close this ticket for now
at the moment it will stay as it is
still thank you for this idea
