### ISSUE TITLE
Notice: iconv(): Wrong charset, conversion from `utf-32le' to `utf-8' is not allowed 

### ISSUE THREAD

**Issue by thomasdcodes** [dockware/dockware#36]
**Describe the bug**
It is impossible to run important commands on the docker machine insight the M1 Docker Apple Silicon Preview 7

**To Reproduce**
Open a connection to the Machine
Execute bin/console theme:change Storefront --all
See Message "Notice: iconv(): Wrong charset, conversion from `utf-32le' to `utf-8' is not allowed"
Command wasn't execute

**Expected behavior**
Command is executed without any notices or error messages

**Desktop (please complete the following information):**
 - OS: MacOS BigSur 11.2
 - Browser: Console
 - Running in "M1 Docker Apple Silicon Preview 7"
- PHP 7.4.12
[PHP Modules]
apc
apcu
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
geoip
gettext
hash
iconv
igbinary
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pgsql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
ssh2
standard
sysvmsg
sysvsem
sysvshm
tideways
tokenizer
xdebug
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache

**Additional context**

**Comment by boxblinkracer** [comment]
Hi

thank you for this

so first thing is, i doubt it has to do with the new M1.
one of the things we use in dockware as fallback is to avoid bind mounting and just use SFTP to get files into the container.
that means its kinda completely isolated, which means its the same container linux on M1 like in all other machines.
...so I'm not saying that its not really due to M1 (could always be a problem expecially with that combination) but that would somehow say the whole docker container concept doesnt work at all on M1 at the moment.

for me it would be interesting how your docker compose file looks like.
does it have bind mounting? does it mount files in probably another encoding?
also is it a contribution version that might be broken?

so the docker compose would be good to see, along with some hints if you upload data or if you just connect into the container

or you could try this

`
docker run dockware/dev:latest
docker exec -it (container-name) bash
php bin/console theme:change Storefront --all
`

if that does not work (i've justed tested it successfully), then Docker might have problems with M1 in generall...(maybe)


cheers
christian

**Comment by thomasdcodes** [comment]
Hey Christian!
Thank you for this quick response.
I tried the 3 commands and also there the notice appears.
I also think that this a problem with the M1. If I try the same with my Intel-Based Mac, everything runs well.
So, you know now, that the problem also occurs with a fresh and unchanged image of your dockware image.

Thank you so much for your help!

Kind regards,
Thomas D.

**Comment by thomasdcodes** [comment]
Yeah @boxblinkracer ! 
The issue seems to be fixed in the new version of M1-Docker (Docker-Desktop 3.1.0).

**Comment by thomasdcodes** [comment]
Now with Docker 3.3.0 the notice is back. But I'm not sure if it is an issue of Dockware. 
Is there another M1 User who can reproduce this issue?

**Comment by martinweinmayr** [comment]
maybe https://github.com/ChristopherDosin can help out?

**Comment by ChristopherDosin** [comment]
Just updated Docker now from 3.1 to 3.3.0 on my M1 - Getting the same issue now.
With Docker version, 3.1 everything was working.

``` 
Compiling theme 65df152301394330ac122a84ac79da15 for sales channel SasTheme

In ParserState.php line 91:

  Notice: iconv(): Wrong charset, conversion from `utf-32le' to `utf-8' is not allowed
```

**Comment by thomasdcodes** [comment]
I also tried a quick fix insight the sabberworm CSS-Parser which I found on the Internet but than a running out of memory Exception appears.
I replaced the line 91 with `return mb_convert_encoding($sUtf32 , 'UTF-8' , 'UTF-16LE');`

**Comment by seriewe** [comment]
Not sure if that helps, but I had this Issue during an update to current SW6.3.5.2 on a Prod System. 

The Solution was like @thomasdcodes wrote to change to `return mb_convert_encoding($sUtf32 , 'UTF-8' , 'UTF-16LE');` 
Line 91 in “vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parsing”

**Comment by ChristopherDosin** [comment]
Yes - The only issue i am getting then is a 

```
mmap() failed: [12] Cannot allocate memory
....
mmap() failed: [12] Cannot allocate memory
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
``

btw: It seems that the issue has something to do with the Bootstrap Theme, maybe the Icons or anything like that because of the encoding.

Because if you remove the Storefront / Bootstrap theme from the styles within the `theme.json` it's compiling.

**Comment by thomasdcodes** [comment]
If I replace the part in Line 91 with `return iconv('utf-32le', $this->sCharset, hex2bin("14200000"));` I got the error named above.
If I run the php interactive shell insight the machine (Both commands are running with php-cli 7.4.16) with the same command: `echo iconv('utf-32le', $this->sCharset, hex2bin("14200000"));` It is working fine and echos '-'.
So the availability to call the function with the given parameters is there.

**Comment by seriewe** [comment]
@ChristopherDosin it's a good hint with the Icons, after I did the change an updated the system I have wired "Chars" appended to my font-awesome Icons. Because I didn't find a solution I switched to a css integration via script tag instead of via scss and compiling the icons into all.css. I will check this point, so it seems that the change to `return mb_convert_encoding($sUtf32 , 'UTF-8' , 'UTF-16LE');`  lead to issues.

**Comment by thomasdcodes** [comment]
I also tried with the new Build of Docker (3.3.0 62345) but the same issue appears.

**Comment by thomasdcodes** [comment]
I also trued with the last build: 3.3.0 62632 → Same issue

**Comment by stevevomwege** [comment]
build: 3.3.0 62632 → Same issue

**Comment by ruffiely** [comment]
Yeah some Problem here. Everything worked fine on my M1. Then I updated osx and Docker 3.1.0 didn't start anymore, so I updated to 3.3.1 today and now I got this iconv() error.

With return mb_convert_encoding($sUtf32 , 'UTF-8' , 'UTF-16LE'); I get out of memory errors. So I guess downgrading Docker?

**Comment by thomasdcodes** [comment]
Problem still alive with Dockware/dev-1.3.6-beta and Docker-Desktop 3.5.2

**Comment by thomasdcodes** [comment]
Problem still alive with Dockware/dev-1.3.6-beta and Docker-Desktop 3.6.0

**Comment by martinweinmayr** [comment]
Ok i will order a m1 mac today and try what i can do!
Thx for reporting all the time 🤟

**Comment by thomasdcodes** [comment]
Wow @martinweinmayr! Thank you so much! 
The astounding thing is, that it ran with Docker Desktop 3.1.0

**Comment by thomasdcodes** [comment]
Also tested with:
Docker-Desktop 4.0.1
MacOS 11.5.2
Dockware dev 1.4

**Comment by martinweinmayr** [comment]
@thomasdcodes cam you give this image a try?

https://hub.docker.com/layers/dockware/dev/6.4.3.1-m1-test/images/sha256-95af49f33bd9f7d0d8a7ef93eb93b65fe2ba2316f64534ded96e2a6f98834f3a?context=explore

**Comment by thomasdcodes** [comment]
Hey @martinweinmayr !
I've tested 6.4.3.1-m1-test with Docker-Desktop 4.0.1, MacOS 11.5.2 and MacOS 11.6. Both failed

**Comment by martinweinmayr** [comment]
after 1 more day diggin into it.
![image](https://user-images.githubusercontent.com/13133302/133628310-16e08460-9599-4ee7-b2b8-d7503dcbccc3.png)

@thomasdcodes can you pls pull and give it another try? would be great

**Comment by thomasdcodes** [comment]
Hey @martinweinmayr !
I ran the dockware/dev:6.4.3.1-m1-test (built on Sept 16th 16:16) and this Version is running well!!!!
Can you tell me something about the issue and when you are going to release it in the "normal" package?
Thank you for your effort!!!!

**Comment by martinweinmayr** [comment]
@thomasdcodes 
in the end we had to build a multicarchitectur build so now you see not only amd64 but also arm64 in the OS/ARCH Dropdown.
Also the official php cotnainers go this way. 
We will start to release all images from dockware with multicarch builds as of today!

This will take up to 48 hours until all builds are finishd.

Many thx for your support and have fun with using dockware on apple m1 :-)

**Comment by FynnZW** [comment]
Had the same problem on an m1-mac, using dockware/dev:6.4.3.1-m1-test solved it. Thanks!

**Comment by martinweinmayr** [comment]
solved since we additionally build for arm architecture.
