### ISSUE TITLE
After Shopware update - watch-admin/watch-storefront not working anymore

### ISSUE THREAD

**Issue by w3work** [dockware/dockware#41]
Hello,

after updating my Shopware local environemnt to the current 6.3.5 version via the Backend Update-Tool, i dont get the watcher working anymore.
This error i get:

```
www-data@1fa10e64a0f4:~$ make watch-storefront
cd /var/www/html && ./bin/build-storefront.sh
/bin/sh: 1: ./bin/build-storefront.sh: Permission denied
makefile:18: recipe for target 'watch-storefront' failed
make: *** [watch-storefront] Error 126
```

It seems there is a permission issue. But how can i change the permissions?

**Comment by martinweinmayr** [comment]
pls try: sudo chown -R www-data:www-data /var/www/html
This will make sure that your user www-data owns all files within the folder

**Comment by w3work** [comment]
> 
> 
> pls try: `sudo chown -R www-data:www-data /var/www/html`
> This will make sure that your user www-data owns all files within the folder

This changed nothing. Still got the error.

I tried some other things and this was the solution here:
`chmod +x bin/build-adminstration.sh`
`chmod +x bin/build-storefront.sh`

inside the /var/www/html folder

**Comment by martinweinmayr** [comment]
1st of all I'm exited that you found a way to fix!

Reagrding our update question we will add a new section to our new docs which will come on monday.

Cause there are more than one way to reach your goals.
