### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by hopatibo** [dockware/dockware#45]
I have started docker with:

 **docker run --rm -p 8080:80 dockware/dev:latest**

this seems to work fine. No error message.

When I open localhost:8080/admin in firefox I can login.
But when I open localhost:8080/  there is an error 500:
-----------------
**Oops! An Error Occurred**
The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
----------------

There is an error message in /var/log/apache/other_vhosts_access.log:
localhost:80 172.17.0.1 - - [25/Feb/2021:16:33:55 +0100] "GET / HTTP/1.1" 500 1063 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0"
But it says nothing about the reason of the error.

In error.log or  access.log there is no message.

**Comment by martinweinmayr** [comment]
knowen issue in shopware 6.
This is caused by saleschannels. Cause there is no saleschannel configured for localhost:8080.

You have to set this in Database (admin woun't let you do this)
and then clear cache.
After that it should work.
