### ISSUE TITLE
Startupscripts

### ISSUE THREAD

**Issue by jniclas** [dockware/dockware#46]
**Is your feature request related to a problem? Please describe.**
On Container startup I have to execute some commands in the container's console to fit the shopware instance to my needs.
But I have to do this manually because I haven't found a way to add custom startup scripts to Dockware.

**Describe the solution you'd like**
Actually, Dockware already has two startup scripts in /var/www/scripts/shopware6 that are executed in entrypoint.sh if the correct envvars are set.
Now, it would be splendid if I could mount my scripts to e.g. /var/www/scripts/custom and the entrypoint.sh would execute all scripts inside it, after the apache service is running (maybe only if a envvar is set to true).

Best regards,
Niclas

**Comment by boxblinkracer** [comment]
hi niclas

funny thing, had the idea last week
so i guess we'll allow it to inject an additional custom bootscript :)

that should help you right?

**Comment by jniclas** [comment]
Hi,

yes, exactly that would help me a lot, would be superb.

Niclas

**Comment by boxblinkracer** [comment]
hi

i've created a new commit today,
there will be 2 points to inject, start + end
https://github.com/dockware/dockware/commit/f34e08ce521a970682b3612aac6a6bdee93a2aeb

its not published on docker hub yet but you could build it on your own if you need it now


cheers
christian

**Comment by jniclas** [comment]
HI,

that was quick - i will try this today. Thank you!

Niclas
