### ISSUE TITLE
Watch-admin crash browser

### ISSUE THREAD

**Issue by szosa** [dockware/dockware#49]
**Describe the bug**
After i run watch-admin, when i try switch element in template (Shopping Experience) the browser are hangs

**To Reproduce**
1. Create new plugin with shopping experience element
2. Run make watch-admin
3. In browser go to localhost:8888/0.0.0.0:8888
4. Go to Shopping Experience -> edit template -> switch element 
5. Browser crash

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7 ( i tried it on Windows 10 and works fine)
 - Browser: chrome and safari
 - Version: lates

**Comment by boxblinkracer** [comment]
Hi

thank you for posting this
i'm not quite sure if this is still a thing, I just tried it and it worked for me

also, I'm not quite sure if this is either a shopware related thing, or just something on your machine

i just tried it with dockware/dev:6.3.5.2 
does this work for you?
if not maybe you can provide a small video?

**Comment by boxblinkracer** [comment]
i havent heard back since June,
and it shuld actually work so i would now close this issue for now
