### ISSUE TITLE
watch-admin - APP_URL is wrong in DEV Version

### ISSUE THREAD

**Issue by wsung** [dockware/dockware#50]
Describe the bug
After I start watch-admin and upload images in Shop Experience, the images are broken.

To Reproduce
- Start dockware #dev (6.3.5.2)
- Start make watch-admin
- Upload an image file in an element. The file exist, but you see a broken image. 

Solution:
The broken image has a URL starts with http://0.0.0.0. That is the problem. It should be same like defined APP_URL. It's working in dockware #contribute. And I found the problem. APP_URL=http://0.0.0.0 should be replaced with APP_URL={{ shopware.url }} ?!?

dockware #dev
cd /var/www/html && APP_URL=http://0.0.0.0 PROJECT_ROOT=/var/www/html APP_ENV=dev PORT=8888 HOST=0.0.0.0 ENV_FILE=/var/www/html/.env ESLINT_DISABLE=true npm run --prefix /var/www/html/vendor/shopware/administration/Resources/app/administration dev

dockware #contribute
cd /var/www/html && PROJECT_ROOT=/var/www/html APP_URL={{ shopware.url }} ESLINT_DISABLE=true PORT=8888 HOST=0.0.0.0 ENV_FILE=/var/www/html/.env npm run --prefix vendor/shopware/platform/src/Administration/Resources/app/administration/ dev

**Comment by boxblinkracer** [comment]
hi

i just tried it myself
and it worked

there are indeed some adjustments to allow these different ways of how shopware required the command to be started across different versions

do you have the latest version of the 6.3.5.2 tag? maybe you can pull it
like i said, it just worked for me

**Comment by boxblinkracer** [comment]
hi
i hope its ok that i close this issue now, in general it worked for me,
maybe its already solved
