### ISSUE TITLE
Watch-Admin not working with Shopware 6.4

### ISSUE THREAD

**Issue by tbkruse** [dockware/dockware#53]
**Describe the bug**
If you use the latest Shopware 6.4 version and wan't to run watch-admin there is an error: "sw-extension-error" is not registered. This is because this is hidden behind a feature flag.

**To Reproduce**
1. Run dockware/dev:latest
2. Connect to docker machine
3. Run make watch-admin
4. Open localhost:8888

**Expected behavior**
The administration opens

**Additional context**
This can be fixed when running bin/console  feature:dump before running make watch-admin. Maybe this call can be included in the makefile

**Comment by jonasfrs** [comment]
thank's for the temporary solution, I have the same problem

**Comment by martinweinmayr** [comment]
solved with newest release.
