### ISSUE TITLE
dockware/dev:latest not working properly on Apple m1 with Docker preview 3.3.2

### ISSUE THREAD

**Issue by ruffiely** [dockware/dockware#54]
**Describe the bug**
The problem is containers which are not based arm64 needs emulation on m1. Unfortunately it seems that docker containers on apple preview docker somehow having memory leaks. The solution would be if we could have a dockware container based von arm64 instead of amd64 This would be awesome!

**To Reproduce**
1. Running docker compose up on M1 Macbook
2. Container starts up normally and works so far
3. Try to compile or change theme via cli on container
4. Segfault: out of memory or problem with iconv utf-8 utf32le

**Expected behavior**
It should be able to use all console commands inside the container without any errors

**Comment by boxblinkracer** [comment]
hi
thank you
we have to look into this

do you already have experience in doing this as arm64 inside github actions?

**Comment by martinweinmayr** [comment]
is solved since we provide arm build additionally
