### ISSUE TITLE
Function definer is wrong

### ISSUE THREAD

**Issue by sebastianwahn** [dockware/dockware#58]
Function definer is wrong.

Creating a product will fail with the error:

`The user specified as a definer ('app'@'%') does not exist"`

This is only the case when the dockware container is started with a custom MySQL user as defined in your docs: 

docker-compose.yml snippet
```
        environment:
            - MYSQL_USER=shopware
            - MYSQL_PWD=shopware
```

The above environments create the user in the database as expected. Although, the product tables trigger definition are not created as this user, but as "app" instead.
If the environments are omitted, and the default root user is used. The definer is "root".

**To Reproduce**
1. Run `docker run --name TEST -d -p '3306:3306' -p '80:80' -e 'MYSQL_USER=shopware' -e 'MYSQL_PWD=shopware' dockware/dev:6.3.5.4`
2. Connect via SQL tool to the database at 3306 User: shopware Password: shopware
3. Check the product table's trigger definition - it states Definer: "app@%" (see screenshot)

Steps to compare without MySQL env:
1. Run `docker run --name TEST2 -d -p '3307:3306' -p '81:80' dockware/dev:6.3.5.4`
2. Connect via SQL tool to the database at 3307 User: shopware Password: shopware
3. Check the product table's trigger definition - it states Definer: "root@%"

**Expected behavior**
When customizing the MySQL user, the definer should be the customized user, not "app". Or, the user "app" should be created also.

**Screenshots**
![image](https://user-images.githubusercontent.com/6577779/120076029-01a9b200-c0a4-11eb-9f46-9ff301c619c9.png)

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**

**Comment by boxblinkracer** [comment]
hi

can you tell me what date your dockware/dev:6.3.5.4 image is?
because that bug has already been fixed...at least a bug like this with the definer

there are indeed required triggers necessary...

here would be the fix which should already bee in 6.3.5.4...weird? or maybe its a new thing...

https://github.com/dockware/dockware/commit/1736dc5d80e12fdb906947f79a507239124e9105

**Comment by sebastianwahn** [comment]
Hi @boxblinkracer for your feedback.

Having a glance at the change it seems related.

I pulled my dockware/dev:6.3.5.4 today and `docker images` says:

```
REPOSITORY                    TAG                   IMAGE ID       CREATED       SIZE
dockware/dev                  6.3.5.4               7584e84dab39   5 weeks ago   2.9GB
```

**Comment by boxblinkracer** [comment]
Hi

thanks

mhm..i've just started the build for dev:6.3.5.4
in about 30 minutes you could try it again

i dont know if you have access with your user, but this would be the pipeline
https://github.com/dockware/dockware/runs/2701494801?check_suite_focus=true

hope it helps

**Comment by sebastianwahn** [comment]
Hi @boxblinkracer,

unfortunately, your pipeline failed.

**Comment by boxblinkracer** [comment]
had to restart it, weird package installation error
so this is the second one ;)
https://github.com/dockware/dockware/actions/runs/888682736

**Comment by boxblinkracer** [comment]
hi,
just wanted to ask if it worked now?

**Comment by sebastianwahn** [comment]
Hi @boxblinkracer,

unfortunately it still appears to be a problem.
I set up the container on a new system with the above command and checked on the "product" tables trigger definitions. They still state "app" as definer.

Best,
Sebastian

**Comment by suc-sgor** [comment]
For everyone still having this problem there are multiple ways to fix this:
1) change MYSQL_USER=App
2) run with bash:
> sudo sed -i 's/DEFINER=`{{ db.user }}`@`%`/DEFINER=`'$MYSQL_USER'`@`%`/g' /tmp/triggers.sql
    sudo mysql --user={{ db.user }} --password={{ db.pwd }} {{ db.database }} < /tmp/triggers.sql
    sudo rm -rf /tmp/triggers.sql

3) recreate the container after fix has been merged.
