### ISSUE TITLE
Unable to Update Entities (e.g. Products)

### ISSUE THREAD

**Issue by Dwayne28** [dockware/dockware#60]
**Describe the bug**
Not able to update existing Products.

When I Look at the developer console (browser) I see:
URL: http://serverIp/api/v2/product/624f23764a064383a1f572c05303bd60
Method: PATCH
StatusCode 400 Bad Request

Response Body is html page with the message:
The following error was encountered:
Invalid Request

Some aspect of the HTTP Request is invalid.  Possible problems:

- Missing or unknown request method
- Missing URL
- Missing HTTP Identifier (HTTP/1.0)
- Request is too large
- Content-Length missing for POST or PUT requests
- Illegal character in hostname; underscores are not allowed

Also encounter this for all other entities.

**To Reproduce**
build any container like mentioned in the docs
1. `docker run --rm -p 80:80 dockware/dev:latest`
2. Login into Admin
3. Go To Products -> select one -> edit
4. edit title add a e.g "1" at the end
5. press save top right -> error 

**Expected behavior**
Able to Update Products

**System**
Tested on Ubuntu 20.10 and Ubuntu 20.04
Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2

Any, Ideas how to solve this.

Thanks in advance

**Comment by martinweinmayr** [comment]
Hi @Dwayne28 ,

can you please call the command "docker images" and the tell me the "created" date of dockware/dev:latest pls?
And also the used shopware version.
And the output from docker logs CONTAINERNAME

As :latest can also be  older version as long as you don't have updated it.

many thx.

**Comment by Dwayne28** [comment]
Hi @martinweinmayr,

thanks for the quick reply. 

Of course docker images outputs for dev created: 7 days ago
Shopware version is: v6.4.1.0 Stable Version

```
 _____   ____   _____ _  ____          __     _____  ______
|  __ \ / __ \ / ____| |/ /\ \        / /\   |  __ \|  ____|
| |  | | |  | | |    | ' /  \ \  /\  / /  \  | |__) | |__
| |  | | |  | | |    |  <    \ \/  \/ / /\ \ |  _  /|  __|
| |__| | |__| | |____| . \    \  /\  / ____ \| | \ \| |____
|_____/ \____/ \_____|_|\_\    \/  \/_/    \_\_|  \_\______|

68 69 20 64 65 76 65 6C 6F 70 65 72 2C 20 6E 69 63 65 20 74 6F 20 6D 65 65 74 20 79 6F 75
6c 6f 6f 6b 69 6e 67 20 66 6f 72 20 61 20 6a 6f 62 3f 20 77 72 69 74 65 20 75 73 20 61 74 20 6a 6f 62 73 40 64 61 73 69 73 74 77 65 62 2e 64 65

*******************************************************
** DOCKWARE IMAGE: dev
** Tag: latest
** Version: 1.3.6-beta
** Built: Mon Jun  7 12:23:56 UTC 2021
** Copyright 2020 dasistweb GmbH
*******************************************************

launching dockware...please wait...

DOCKWARE: setting timezone to Europe/Berlin...

Current default time zone: 'Europe/Berlin'
Local time is now:      Tue Jun 15 08:35:10 CEST 2021.
Universal Time is now:  Tue Jun 15 06:35:10 UTC 2021.

-----------------------------------------------------------
DOCKWARE: deactivating Xdebug...
-----------------------------------------------------------
DOCKWARE: switching to composer 2...
Upgrading to version 2.1.3 (stable channel).

Use composer self-update --rollback to return to version 2.0.11
-----------------------------------------------------------
DOCKWARE: restarting SSH service....
 * Restarting OpenBSD Secure Shell server sshd
   ...done.
-----------------------------------------------------------
DOCKWARE: starting MySQL....
 * Starting MySQL database server mysqld
   ...done.
-----------------------------------------------------------
DOCKWARE: starting mailcatcher....
Starting MailCatcher
==> smtp://0.0.0.0:1025
/var/lib/gems/2.5.0/gems/thin-1.5.1/lib/thin/server.rb:104: warning: constant ::Fixnum is deprecated
==> http://0.0.0.0:1080/
*** MailCatcher runs as a daemon by default. Go to the web interface to quit.
-----------------------------------------------------------
DOCKWARE: starting cron service....
 * Starting periodic command scheduler cron
   ...done.
-----------------------------------------------------------
DOCKWARE: switching to PHP 7.4...
-----------------------------------------------------------
DOCKWARE: testing and starting Apache...
Syntax OK
 * Restarting Apache httpd web server apache2
   ...done.
-----------------------------------------------------------

WOHOOO, dockware/dev:latest IS READY :) - let's get started
-----------------------------------------------------
DOCKWARE CHANGELOG: /var/www/CHANGELOG.md
PHP: PHP 7.4.20 (cli) (built: Jun  4 2021 21:24:37) ( NTS )
Apache DocRoot: /var/www/html/public
ADMINER URL: http://localhost/adminer.php
MAILCATCHER URL: http://localhost/mailcatcher
PIMPMYLOG URL: http://localhost/logs
SHOP URL: http://localhost
ADMIN URL: http://localhost/admin

What's new in this version? see the changelog for further details
https://www.shopware.com/de/changelog/
```

**Comment by Dwayne28** [comment]
solved

**Comment by martinweinmayr** [comment]
Can you tell us what the solution was?

**Comment by Dwayne28** [comment]
Of course, 

We needed to set up a demo shopware for one of our customers on their machines so we used a vpn with specific proxy settings and these didn't allow http-method: PATCH (that's the reason why everything else worked fine). We even set up shopware on three different machines with different docker shopware images (all while connected to the proxy) always same problem.

Maybe you could add a troubleshoot section to mention these things even if they had nothing to do with the solution you providing.

Thanks for your effort.
