### ISSUE TITLE
[Config] Redis Configuration

### ISSUE THREAD

**Issue by Dwayne28** [dockware/dockware#62]
I want to use redis as caching mechanism for app and session cache. I followed the instructions under: 
https://docs.dockware.io/faq/redis
+ 
```
$ php bin/console cache:clear
$ php bin/console theme:compile
```

But doesn't seem to have any effect. 

I was wondering if I need to do additional configuration
inside the container besides the editing of the .env file
looking into:
/config/services/defaults.xml
/config/packages/framework.yaml
php.ini

I'm using the dockware/dev:6.4.1.0 with PHP_Version=7.4
the .env is still set to development and not prod.

Thanks in advance

Best regards

**Comment by boxblinkracer** [comment]
hi there

do you have a redis container? 
we have a guide on the website

maybe it helps
https://docs.dockware.io/faq/redis

at least it worked with an earlier version ;) if not let me know please

cheers

**Comment by boxblinkracer** [comment]
ah sry i missed that where you wrote it

maybe cache clearing?
otherwise i would need to test it in the next days

**Comment by boxblinkracer** [comment]
Hi

sorry for this,
i think you need to configure it correctly for Shopware
https://developer.shopware.com/docs/guides/hosting/performance/caches#example-replace-some-cache-with-redis

**Comment by boxblinkracer** [comment]
I've updated the documentation
I think then it should all work

I also don't know if this issue is still existing, so I would close it for now
feel free to open it again
