### ISSUE TITLE
Pimp my log does not work with PHP 8

### ISSUE THREAD

**Issue by raphaelboos** [dockware/dockware#66]
**Pimp my log does not work with PHP 8**
Dockware images now support PHP 8.
The current pimp my log version makes use of the php function get_magic_quotes_gpc() - this was already deprecated in PHP 7.4 and was removed in PHP 8.

**To Reproduce**
1. Start dockware/dev:latest with PHP_VERSION=8.0
2. Open logs in any browser http://localhost/logs
3. Fatal error: Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /var/www/pimpmylog/inc/global.inc.php:160 Stack trace: #0 /var/www/pimpmylog/index.php(11): include_once() #1 {main} thrown in /var/www/pimpmylog/inc/global.inc.php on line 160

**Comment by raphaelboos** [comment]
Hi Christian,

 

thanks for answering.


Dev logs should be in bind mounted src/var/log on host
Webserver logs should be in container /var/log/apache2

 

Right?

 

Regards Raphael

Von: Christian ***@***.***> 
Gesendet: Mittwoch, 21. Juli 2021 15:29
An: dockware/dockware ***@***.***>
Cc: Raphael Boos ***@***.***>; Author ***@***.***>
Betreff: Re: [dockware/dockware] Pimp my log does not work with PHP 8 (#66)

 

hi
oh i think i saw that once
yeah thas is very annoying....ill mark it as "bug" so we can fix it hopefully
until that, you can use the server logs directly

do you know where to find these?

**Comment by boxblinkracer** [comment]
hi

yes almost

server logs are in /etc/logs/php

there are the php error logs :)

**Comment by boxblinkracer** [comment]
Hi

good news, we've added a custom patch and its now working,
should come with the next release soon

**Comment by boxblinkracer** [comment]
The dockware v1.4 versions do now contain a custom made patch to have it working on PHP8
thanks for creating this issue :)
