### ISSUE TITLE
Support for MYSQL 8

### ISSUE THREAD

**Issue by alexschwarz89** [dockware/dockware#67]
**Is your feature request related to a problem? Please describe.**
As MySQL 8 is stable and production servers are using it, there are problems if local database is running MySQL 5.7.

**Describe the solution you'd like**
Offer a possibility to use MySQL 8 with dockware.

**Comment by boxblinkracer** [comment]
Hi there

thank you for your message

you could just use a second MySql containere. that would be the recommended way for special setups

i hope this helps you
