### ISSUE TITLE
bin/console theme:compile doesn't work

### ISSUE THREAD

**Issue by larsbo** [dockware/dockware#7]
Not sure if this is related to shopware or the docker image but executing `bin/console theme:compile` just print out
`Start theme compilation` and nothing happens (execution hangs forever). The storefront assets will be missing after stopping the execution.

Running `bin/build-js.sh` works fine, but the "Inter" font files are always missing. I found this related shopware issue: https://github.com/shopware/development/issues/59
Thats why I  tried the `theme:compile` command 😉

**Comment by boxblinkracer** [comment]
Hi

thanks for adding this issue

I just tried it on my end and it works
(see screenshot)

could you verify that by starting a new container with

docker run --rm -p 80:80 dockware/dev:latest

and then docker exec into the container (name from "docker ps")

if that works, then maybe its a problem in your project?


cheers
christian

<img width="627" alt="Screenshot 2020-07-01 at 08 16 45" src="https://user-images.githubusercontent.com/5579326/86209695-6c402e00-bb73-11ea-9ac2-ae35102f17f2.png">

**Comment by larsbo** [comment]
I gave my previous container another try and it finished the execution after 10min 😂 

Now I tried a fresh container and it took a long time again:
```
www-data@b8dbbcf4ce31:~/html$ bin/console theme:compile
Start theme compilation

 ! [NOTE] Took 243.627086 seconds
```

Host system:
Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

Docker Resources:
CPUs: 3 (of 6) (Docker let me choose up to 12 here?)
RAM: 6GB (of 16GB)
SWAP: 1GB

**Comment by larsbo** [comment]
ok, increasing the cpus and memory did the trick 😃 

CPUs: 6
RAM: 8GB
```
www-data@51127301bcb0:~/html$ bin/console theme:compile
Start theme compilation

 ! [NOTE] Took 26.499434 seconds
```

**Comment by boxblinkracer** [comment]
Hi

awesome, great it working, thanks for letting us know

still its weird, i don't need that much resources to build it

i have 3 CPUs, 5,5GB RAM, MAC OS X

anyway :) i think we can close this right?


cheers
christian

**Comment by larsbo** [comment]
yeah... thought it would be enough, too 😄 

thanks for the fast support, issue can be closed!

**Comment by boxblinkracer** [comment]
alright
you're welcome :)
