### ISSUE TITLE
Can#t open localhost on windows

### ISSUE THREAD

**Issue by BlueWolf-Produktion** [dockware/dockware#75]
Hi,
i just get Docker and tried to start the DEV machine 

V:\Docker\SW6.4.3>docker-compose up -D
[+] Running 1/1
 - Container shopware  Started                                                                                     3.3s
Attaching to shopware
shopware  |
shopware  | Current default time zone: 'Europe/Berlin'
shopware  | Local time is now:      Wed Aug 18 17:43:29 CEST 2021.
shopware  | Universal Time is now:  Wed Aug 18 15:43:29 UTC 2021.
shopware  |
shopware  | -----------------------------------------------------------
shopware  | DOCKWARE: deactivating Xdebug...
shopware  | -----------------------------------------------------------
shopware  | DOCKWARE: restarting SSH service....
shopware  |  * Restarting OpenBSD Secure Shell server sshd
shopware  |    ...done.
shopware  | -----------------------------------------------------------
shopware  | DOCKWARE: starting MySQL....
shopware  |  * Starting MySQL database server mysqld
shopware  |    ...done.
shopware  | -----------------------------------------------------------
shopware  | DOCKWARE: starting mailcatcher....
shopware  | Starting MailCatcher v0.8.1
shopware  | ==> smtp://0.0.0.0:1025
shopware  | /var/lib/gems/2.5.0/gems/thin-1.5.1/lib/thin/server.rb:104: warning: constant ::Fixnum is deprecated
shopware  | ==> http://0.0.0.0:1080
shopware  | *** MailCatcher runs as a daemon by default. Go to the web interface to quit.
shopware  | -----------------------------------------------------------
shopware  | DOCKWARE: starting cron service....
shopware  |  * Starting periodic command scheduler cron
shopware  |    ...done.
shopware  | -----------------------------------------------------------
shopware  | DOCKWARE: switching to PHP 7.4...
shopware  | -----------------------------------------------------------
shopware  | DOCKWARE: testing and starting Apache...
shopware  | Syntax OK
shopware  |  * Restarting Apache httpd web server apache2
shopware  |    ...done.
shopware  | -----------------------------------------------------------
shopware  |
shopware  | WOHOOO, dockware/dev:latest IS READY :) - let's get started
shopware  | -----------------------------------------------------
shopware  | DOCKWARE CHANGELOG: /var/www/CHANGELOG.md
shopware  | PHP: PHP 7.4.22 (cli) (built: Jul 30 2021 13:07:59) ( NTS )
shopware  | Apache DocRoot: /var/www/html/public
shopware  | ADMINER URL: http://localhost/adminer.php
shopware  | MAILCATCHER URL: http://localhost/mailcatcher
shopware  | PIMPMYLOG URL: http://localhost/logs
shopware  | SHOP URL: http://localhost
shopware  | ADMIN URL: http://localhost/admin
shopware  |
shopware  | What's new in this version? see the changelog for further details
shopware  | https://www.shopware.com/de/changelog/
shopware  |

Changed the port from 80 to 8080, but localhost:8080 or 127.0.0.1:8080 only get a ERR_EMPTY_RESPONSE
With ftp i have access to the container.

What now?

**Comment by boxblinkracer** [comment]
can you show me a screenshot of the output of 
"docker ps" in your terminal please?

**Comment by BlueWolf-Produktion** [comment]
I gave it up, one reason is that docker always need c:
I got a running DEV of shopware 6 under VirtualBox - thats all i need at this time.
thanks, docker under windows 10 is removed
