### ISSUE TITLE
Update Node to v14

### ISSUE THREAD

**Issue by boxblinkracer** [dockware/dockware#81]
should be updated to v14

but we need to see if old shopware versions still work before doing this

**Comment by theuers** [comment]
Hello,

love your work, big fan of the project. 
Just my two cents regarding to this feature.

This would be a great feature, especially if the node-version would be configurable ([changes to shopware/platform](https://github.com/shopware/platform/commit/e39bf73c2c5c0a838ca89870dea9efeb61bb0d34) suggest shopware 6.5.x might have node 16 as strict requrement).

Shopware uses [nvm](https://github.com/nvm-sh/nvm), which could be used in this project as well.
[Link to usage of nvm in shopware/platform](https://github.com/shopware/platform/blob/6a6ed615733cc6a4a82db9b02b7fe5a246c58c2e/.github/workflows/02-unit.yml#L86)
[Another usage of nvm in shopware/platform](https://github.com/shopware/platform/blob/1955077a39809e49b6e80d44a58826a6584a12df/.gitlab/lib/scripts.yml#L7)

**Comment by boxblinkracer** [comment]
Hi there
thanks for your kind words

that sounds great
ill check it out, thx

**Comment by boxblinkracer** [comment]
oh its so good
just playing around with it and indeed the solution for what i am trying to add

**Comment by theuers** [comment]
Hi,

this is wonderful news!
I am happy that I could contribute something, thank you for the update!

**Comment by boxblinkracer** [comment]
:) great to hear

also, had a hard time using nvm, because it seemed to have different bash scopes in dockerfile, entrypoint and when you actually connect into the container...so its not yet done, but in a different feature branch...
i think i was just too dumb last week :D ill give it a retry, just if its not rolled out soon and you might be wondering what is going on

**Comment by theuers** [comment]
Hi,

thank you for the update!

I was testing nvm in a dockware image before initially commenting but could not get it to work properly (testing if the solution is feasible, it wasn't pretty). 

Thank you for keeping me in the loop and mentioning the feature branch!

**Comment by boxblinkracer** [comment]
alright, hope to have it working sooner or later :)

**Comment by boxblinkracer** [comment]
released with nvm switching :)
