### ISSUE TITLE
Composer accidentally always fetched in entrypoint

### ISSUE THREAD

**Issue by boxblinkracer** [dockware/dockware#89]
the default value of the composer version is never "unassigned".

therefore there will always be a composer download in the entrypoint which means it cannot be used offline anymore

**Comment by m4m-simon** [comment]
because of that i can not start the docker container anymore

`curl error 7 while downloading https://getcomposer.org/versions: Failed to connect to getcomposer.org port 443: Connection timed out`

THIS NEEDS ATTENTION and a fast fix!

@boxblinkracer @martinweinmayr

**Comment by boxblinkracer** [comment]
published and ready :)
